Fix the issues reported by vet (tip branch)
cycloidio/raws pull request #13
Opened 2018-01-25 18:32 UTC by ifraixedes

Fix the issues reported by the go tool vet of the tip branch.
The issues were reported by the CI, because it runs the with the tip
branch too, a part of the Go 1.8.1 version.

This should fix the issues that you have indicated in https://github.com/cycloidio/raws/pull/9#pullrequestreview-91598944
This changes don't belong to #11

2018-01-26 08:07 UTC, xlr-8 requested changes
I know 'session' isn't the best, but 'ses' is also an AWS service regarding mailing. I feel like calling 'session' - 'ses' for a library handling AWS services is more confusing than calling it 'session'.

ref: https://aws.amazon.com/ses/

2018-01-26 08:20 UTC, ifraixedes commented
I will rename it, however it doesn't report such issue by `go vet` because the _ses_ AWS package isn't imported.
I  mostly applied changes to shut up the CI

2018-01-26 09:22 UTC, ifraixedes commented
I renamed them to `sess`

2018-01-29 09:59 UTC, xlr-8 approved these changes

2018-01-29 12:22 UTC, merged