Added: 'ctx' to the missing methods on the README
cycloidio/raws pull request #41
Opened 2019-02-18 07:46 UTC by xescugc

It was basically updated on the code but we forgot the README examples.

Closes #39

2019-02-22 07:54 UTC, xlr-8 commented
Did you test that the copy paste of such code would work?

2019-02-22 09:12 UTC, xescugc commented
No I did not, but you can pass nil as a parameter on those, so yes it works.

2019-02-26 09:42 UTC, xlr-8 requested changes
Sorry forgot to submit!
I'll be fully of bad-faith and blame GH button :D

2019-02-26 09:42 UTC, xlr-8 commented on README.md
> +ctx := context.Background()
If we just copy paste those pieces, it's confusing and wrong, because `var ctx = context.Background()` is declared right above, so that would lead to compilation error.

2019-02-26 09:42 UTC, xlr-8 commented on README.md
L.53 (right bellow), the example file doesn't exist anymore.
However if we want to provide a minimalistic working file this could do:

```go
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/cycloidio/raws"
)

func main() {
	var config *aws.Config = nil
	var accessKey string = "xxxxxxxxxxxxxxx"
	var secretKey string = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
	var region []string = []string{"eu-*"}
	var ctx = context.Background()

	c, err := raws.NewAWSReader(ctx, accessKey, secretKey, region, config)
	if err != nil {
		fmt.Printf("Error while getting NewConnector: %s\n", err.Error())
		return
	}

	elbs, _ := c.GetLoadBalancersV2(ctx, nil)
	fmt.Println(elbs)
	instances, _ := c.GetInstances(ctx, nil)
	fmt.Println(instances)
	vpcs, _ := c.GetVpcs(ctx, nil)
	fmt.Println(vpcs)
	return
}
```

2019-07-11 10:51 UTC, xlr-8 approved these changes

2019-07-11 11:21 UTC, xescugc commented
Merge as I only rebased.

2019-07-11 11:21 UTC, merged