README: Add a warining of UNMAINTAINED
cycloidio/raws pull request #53
Opened 2019-12-18 09:49 UTC by xescugc

So it's easy to identify and where to go if a similar library it's neede

2019-12-18 16:53 UTC, xlr-8 requested changes
Rest LGTM

2019-12-18 16:53 UTC, xlr-8 commented on README.md
> +It has several different things and it's development it's to fit TerraCognita needs, the main difference is that it does not support multi regions anymore, it was a blocking point if you wanted to us
I'd rephrase:

```
It has several differences and its development is made to fit TerraCognita needs. The main difference being no more multi-region, as it was blocking for fetching more results due to pagination.
```

2019-12-18 22:07 UTC, xescugc commented
Done

2019-12-19 08:49 UTC, xlr-8 approved these changes

2019-12-19 08:49 UTC, xlr-8 commented
RS & good to go

2019-12-19 11:17 UTC, merged