Billing: create a first draft of all components
cycloidio/raws pull request #6
Opened 2017-08-04 14:31 UTC by xlr-8

Currently the backend used is DynamoDB, but it shouldn't be too difficult to replace it in the future, the logic would remain the same.
    
Checker:
The checker is responsible for checking the hash of the S3 file and the value in the dynamoDB. If those values are identical then no import is needed.
    
Downloader:
The downloader is responsible for downloading and unzipping the billing file is the different given paths.
    
Loader:
The loader reads the unzipped file and loads its data into a go struct, in order to be consumed progressively via the 'injector'.
    
Injector:
The injector create the differents entries in dynamoDB for both the report (in order to store the hash) and for the records (all fields are being injected into the database), some extra one are also given such as: a UUID or the name of the report the record comes from.
    
Manager:
The manager is the one calling the different component, it simply takes the 2 AWS accounts (S3 & DynamoDB) as parameters, as well as the 'date' and the 'bucket' it is supposed to import the data from.

2017-08-07 19:53 UTC, xescugc reviewed
I did not check the logic, just the code, to check the logic I'll need more time :). As everyting is on interfaces could be really easy to make test without really using real data, just mocking.

2017-08-07 19:53 UTC, XescuGC commented on billing/checker.go
> +		return fmt.Errorf("Found too many objects matching (%d)\n", len(objectsOutput))
I would not add the `\n` at the end of the error

2017-08-07 19:53 UTC, XescuGC commented on billing/downloader.go
> +	defer fd.Close()
The `defer fd.Close()` should go after checking the errors, because if there is any error the `fd` is nil and you will have a null pointer exception.

2017-08-07 19:53 UTC, XescuGC commented on billing/downloader.go
> +		return "", fmt.Errorf("Couldn't create file '%s': %+v", dest, err)
Just a simple comment hehe `'%s'` is the same as `%q`

2017-08-07 19:53 UTC, XescuGC commented on billing/loader.go
> +type fieldMapper map[string]map[interface{}]map[string]interface{}
OMG haha

2017-08-07 19:53 UTC, XescuGC commented on billing/loader.go
> +	file, err := os.Open(billingFile)
I think it should be closed the `file` too

2017-08-07 19:53 UTC, XescuGC commented on billing/loader.go
> +	invoicePeriod, err := time.Parse("2006-02", dateMonthMatcher.FindString(billingFile))
Which is the format of the `billingFile`?

2017-08-08 06:22 UTC, xlr-8 commented on billing/loader.go
> +	invoicePeriod, err := time.Parse("2006-02", dateMonthMatcher.FindString(billingFile))
The naming format is: '$ACCOUNT_ID-aws-billing-detailed-line-items-with-resources-and-tags-$YEAR-$MONTH.csv.zip' - but here it's the version without .zip extension.

I think I mentioned there: https://github.com/cycloidio/youdeploy/issues/17

2017-08-08 06:26 UTC, xlr-8 commented on billing/loader.go
> +type fieldMapper map[string]map[interface{}]map[string]interface{}
This type has been removed, because I managed to worked around it previously with reflection; I forgot to remove it though :D - so no need for it!

2017-08-08 06:41 UTC, xlr-8 commented on billing/loader.go
> +	file, err := os.Open(billingFile)
Now done in the caller method - the fd is saved and closed after processing.

2017-08-08 06:52 UTC, XescuGC commented on billing/loader.go
> +type fieldMapper map[string]map[interface{}]map[string]interface{}
Thanks GOD ahahaha

2017-08-08 07:02 UTC, XescuGC commented on billing/loader.go
> +	invoicePeriod, err := time.Parse("2006-02", dateMonthMatcher.FindString(billingFile))
It's not possible that $ACCOUNT_ID has this format no?

2017-08-18 06:14 UTC, xlr-8 commented
Different points were discussed on this:
* If we wanted to make it a more 'library' style, then we should make the structure more agnostic of the backend - e.g. moving some check method to the backend, so that it is easily changeable
* The code should also reside somewhere else than here, as this is a library, where as this project isn't

2017-08-18 07:09 UTC, xescugc requested changes
I agree with the notes you said before.

For the code I think you should add documentation to all the public methods/interfaces and the privat ones that you consider important, which also may include a `doc.go` on the `billing/` to describe the global usecase of the package `billing`

2017-08-21 08:45 UTC, xlr-8 commented
Would that do to write a proper README and create an issue for the documentation part?

2017-08-21 08:48 UTC, xlr-8 commented
Also another idea was to split the interfaces from the code into different package such as 'package X' and 'package XIface', a bit like AWS is doing with: 

```
"github.com/aws/aws-sdk-go/service/dynamodb/"
"github.com/aws/aws-sdk-go/service/dynamodb/dynamodbiface"
```

2017-08-28 10:19 UTC, XescuGC commented
I've reviwed the code and sems correct except some syntax that I don't like, I did not mention it on the code because I think thik it'll be usefull for you to look at them, run a [linter](https://github.com/golang/lint) to the code and you'll see them, basically are: 
* Missing documentation
* Assigning default values to types, `var a string = ""` or `var a int = 0`

2017-08-28 17:51 UTC, xlr-8 commented
As mentioned the documentation would be open as an issue, for the rest many lint errors have been fixed in the last commit - not all of them though - please read the git commit message for more information. Thanks for the review!

2017-08-29 06:34 UTC, XescuGC commented
> Some have not been modified such as some else+return or variable naming
- such as the ones containing 'Id' because that is dependant of the CSV
file provided by AWS.

Why not the else+return? and the namig of the CSV does not depend on the AWS, you read the data and set it no? you can name it whatever you want hehe but ok.

2017-08-29 06:34 UTC, xescugc approved these changes

2017-08-29 10:23 UTC, xlr-8 commented
Project & Issues relative to this PR have been opened here: https://github.com/cycloidio/aws-billing, closing this one.

2017-08-29 10:23 UTC, closed without merging